export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

import ClientWrapper from '@/src/components/ClientWrapper'
import '../globals.css'

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return <ClientWrapper>{children}</ClientWrapper>
}
