import AppContentsCard from '@/components/AppContentsCard'
import ListItem from '@/components/about-icons/ListItem'

export default function FireResistance() {
    return (
        <AppContentsCard title={'錠前の種類'} isNoBorder>
            <ul>
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="ダイヤル式"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="テンキー式：暗証番号1種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="テンキー式：暗証番号2種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="テンキー式：暗証番号5種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="テンキー式：暗証番号10種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="指紋照合式：10指登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="ICタグ式（接触型）：10種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="ICカードロック式）：10種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="ICカードロック式）：500種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="顔認証ロック式：500種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="スマートフォンロック式：10種登録"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="マグロック式"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="シリンダー式"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="内臓シリンダー式"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="リゼロ・ロック式"
                />
                <ListItem
                    imagePath="s_icon_f120.svg"
                    description="ダイヤルナンバーロック式"
                    isLast
                />
            </ul>
        </AppContentsCard>
    )
}
